const express = require('express')
const router = express.Router()
const admincontroller = require('../controllers/admincontroller')
const {adminAuth,userAuth} = require('../middlewares/auth')
const categorycontroller = require('../controllers/categorycontroller')
const productcontroller = require('../controllers/productcontroller')
router.get('/login',admincontroller.loadlogin)
router.post('/login',admincontroller.loginverification)
router.get('/dashboard',adminAuth,admincontroller.dashboard)
router.get('/users',admincontroller.loadusers)
router.post('/blockUnblock/:id',admincontroller.blockUnblock)
router.get('/user/Search',admincontroller.searchuser)
router.post('/user/clear',admincontroller.clear)
router.get('/category/search',categorycontroller.categorySearch)
router.get('/logout',admincontroller.logout)
router.get('/addcategory',categorycontroller.addcategorypage)
router.get('/Category',adminAuth,categorycontroller.categoryInfo)
router.post('/category/clear',categorycontroller.categoryclear)
router.post('/addcategory',categorycontroller.addcategory)
router.delete('/Category/categories/:id',categorycontroller.deleteCategory)
router.get('/deleteCategory',categorycontroller.loadDeleteCategory)
router.get('/addproduct',productcontroller.addproductpage)
router.get('/product',productcontroller.productpage)
router.post('/upload',productcontroller.addproduct)
module.exports = router;